import { Goal, Habit, Journey, LifeScoreData, TimelineEvent, UserProfile, WeeklyPlan } from '@/types';

export const INITIAL_USER: UserProfile = {
  name: 'Matheus',
  avatarText: 'M',
  role: 'Membro Fundador',
  isOnboarded: true,
  target12Months: 'Correr minha primeira meia maratona, alcançar R$ 50k investidos e assumir como Head de Produto sem abrir mão do equilíbrio pessoal.',
  primaryFocusArea: 'corpo',
  completedWeeksCount: 14,
};

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-1',
    title: 'Correr Meia Maratona (21 km)',
    description: 'Completar os 21km na Meia Maratona com ritmo confortável e sem lesões.',
    lifeArea: 'corpo',
    status: 'active',
    startDate: '2026-01-10',
    targetDate: '2026-10-18',
    progress: 48,
    whyItMatters: 'Provar para mim mesmo que consigo sustentar disciplina e resistência de longo prazo na minha saúde física.',
    milestones: [
      { id: 'm1-1', title: 'Correr 5 km contínuos abaixo de 30 min', targetValue: '5 km', completed: true, order: 1 },
      { id: 'm1-2', title: 'Completar treino longo de 10 km', targetValue: '10 km', completed: true, order: 2 },
      { id: 'm1-3', title: 'Alcançar 15 km com ritmo constante de 5:45/km', targetValue: '15 km', completed: false, order: 3 },
      { id: 'm1-4', title: 'Completar os 21 km na prova oficial', targetValue: '21 km', completed: false, order: 4 },
    ],
    actions: [
      { id: 'a1-1', title: 'Treino de rodagem leve de 6 km', completedToday: true },
      { id: 'a1-2', title: 'Exercícios de fortalecimento de joelho e core', completedToday: false },
    ],
  },
  {
    id: 'goal-2',
    title: 'Reserva & Patrimônio de R$ 50.000',
    description: 'Construir a reserva financeira de segurança em renda fixa de liquidez diária e aportes consistentes.',
    lifeArea: 'dinheiro',
    status: 'active',
    startDate: '2025-11-01',
    targetDate: '2026-12-31',
    progress: 72,
    whyItMatters: 'Ter tranquilidade mental e autonomia para tomar decisões de carreira sem pressão financeira imediata.',
    milestones: [
      { id: 'm2-1', title: 'Primeiros R$ 15.000 acumulados', targetValue: 'R$ 15k', completed: true, order: 1 },
      { id: 'm2-2', title: 'Bater R$ 30.000 em reserva líquida', targetValue: 'R$ 30k', completed: true, order: 2 },
      { id: 'm2-3', title: 'Atingir R$ 40.000 com aportes automáticos mensais', targetValue: 'R$ 40k', completed: true, order: 3 },
      { id: 'm2-4', title: 'Meta final: R$ 50.000 consolidados', targetValue: 'R$ 50k', completed: false, order: 4 },
    ],
    actions: [
      { id: 'a2-1', title: 'Aportar R$ 400 da economia da semana', completedToday: false },
    ],
  },
  {
    id: 'goal-3',
    title: 'Transição para Head de Produto',
    description: 'Liderar a estratégia do produto principal e estruturar o time de crescimento.',
    lifeArea: 'carreira',
    status: 'active',
    startDate: '2026-02-01',
    targetDate: '2026-09-30',
    progress: 65,
    whyItMatters: 'Subir de patamar profissional, influenciar a visão executiva e aumentar meu rendimento anual.',
    milestones: [
      { id: 'm3-1', title: 'Apresentar plano de produto do 1º semestre para diretoria', completed: true, order: 1 },
      { id: 'm3-2', title: 'Concluir mentoria com 2 líderes da indústria', completed: true, order: 2 },
      { id: 'm3-3', title: 'Entregar o lançamento da nova arquitetura de produto', completed: false, order: 3 },
    ],
    actions: [
      { id: 'a3-1', title: 'Revisar métricas de retenção antes da reunião de diretoria', completedToday: true },
    ],
  },
  {
    id: 'goal-4',
    title: 'Ritmo Saudável de Presença Familiar',
    description: 'Garantir noites livres sem tela de trabalho e refeições com quem importa.',
    lifeArea: 'vida',
    status: 'active',
    startDate: '2026-01-01',
    targetDate: '2026-12-31',
    progress: 80,
    whyItMatters: 'Sucesso profissional sem paz em casa e presença real não vale o sacrifício.',
    milestones: [
      { id: 'm4-1', title: 'Instituir domingos sagrados sem notebook', completed: true, order: 1 },
      { id: 'm4-2', title: 'Jantar semanal com meus pais sem distrações', completed: true, order: 2 },
    ],
    actions: [
      { id: 'a4-1', title: 'Desconectar notificações de trabalho às 19h30', completedToday: false },
    ],
  },
];

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'habit-1',
    title: 'Treino de Força ou Corrida',
    lifeArea: 'corpo',
    frequencyPerWeek: 4,
    daysCompletedThisWeek: [1, 2, 4],
    targetDescription: '4x por semana · 60 min',
    streakWeeks: 9,
    iconName: 'Dumbbell',
  },
  {
    id: 'habit-2',
    title: 'Aporte Financeiro Semanal',
    lifeArea: 'dinheiro',
    frequencyPerWeek: 1,
    daysCompletedThisWeek: [5],
    targetDescription: '1x por semana · R$ 150 a R$ 300',
    streakWeeks: 14,
    iconName: 'Coins',
  },
  {
    id: 'habit-3',
    title: 'Bloco de Foco Profundo Sem Notificações',
    lifeArea: 'carreira',
    frequencyPerWeek: 5,
    daysCompletedThisWeek: [1, 2, 3, 4],
    targetDescription: '5x por semana · 90 min',
    streakWeeks: 6,
    iconName: 'Crosshair',
  },
  {
    id: 'habit-4',
    title: 'Leitura de Livro ou Diário Noturno',
    lifeArea: 'vida',
    frequencyPerWeek: 6,
    daysCompletedThisWeek: [1, 2, 3, 5],
    targetDescription: '6x por semana · 20 min',
    streakWeeks: 4,
    iconName: 'BookOpen',
  },
];

export const INITIAL_JOURNEYS: Journey[] = [
  {
    id: 'journey-1',
    title: '30 Dias de Movimento Consciente',
    description: 'Prática ininterrupta de atividade física moderada ou intensa todo santo dia.',
    lifeArea: 'corpo',
    totalDays: 30,
    currentDay: 17,
    slipDays: 1,
    status: 'active',
    badgeText: 'Dia 17 de 30 · Trajetória em andamento',
  },
  {
    id: 'journey-2',
    title: '21 Dias Sem Telas na Cama',
    description: 'Deixar o celular na sala após as 22h30 para um descanso fisiológico profundo.',
    lifeArea: 'vida',
    totalDays: 21,
    currentDay: 12,
    slipDays: 0,
    status: 'active',
    badgeText: 'Dia 12 de 21 · Foco impecável',
  },
  {
    id: 'journey-3',
    title: '90 Dias Sem Compras por Impulso',
    description: 'Aplicar a regra dos 3 dias de reflexão antes de qualquer compra acima de R$ 150.',
    lifeArea: 'dinheiro',
    totalDays: 90,
    currentDay: 44,
    slipDays: 2,
    status: 'active',
    badgeText: 'Dia 44 de 90 · Construção sólida',
  },
];

export const INITIAL_WEEKLY_PLAN: WeeklyPlan = {
  id: 'plan-w14',
  weekNumber: 14,
  year: 2026,
  northStarGoal: 'Manter a constância do volume de treinos e fechar a tese de produto sem atrasar o sono.',
  areaPriorities: {
    corpo: 'Completar 4 treinos na semana e rodagem de 12 km no sábado.',
    dinheiro: 'Aportar R$ 350 na reserva líquida e evitar delivery durante a semana.',
    carreira: 'Finalizar o documento de estratégia de produto para alinhamento.',
    vida: 'Jantar de aniversário com a família na sexta-feira com atenção plena.',
  },
  isCompleted: false,
};

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 't-1',
    date: '2024-03-15',
    year: 2024,
    month: 'Março',
    title: 'Primeiro dia de musculação e decisão de mudança',
    description: 'Iniciei os treinos com peso corporal e decidi que a saúde seria prioridade não negociável.',
    type: 'habit_streak',
    lifeArea: 'corpo',
    tag: 'Começo',
  },
  {
    id: 't-2',
    date: '2024-08-20',
    year: 2024,
    month: 'Agosto',
    title: 'Primeiros R$ 10.000 investidos',
    description: 'Bati a primeira meta financeira e criei a conta de investimentos dedicada.',
    type: 'milestone',
    lifeArea: 'dinheiro',
    tag: 'Marco Financeiro',
  },
  {
    id: 't-3',
    date: '2025-02-01',
    year: 2025,
    month: 'Fevereiro',
    title: 'Promoção para Gerente de Produto Sênior',
    description: 'Assumi a liderança da tribo de experiência e novos canais.',
    type: 'achievement',
    lifeArea: 'carreira',
    tag: 'Carreira',
  },
  {
    id: 't-4',
    date: '2025-07-12',
    year: 2025,
    month: 'Julho',
    title: 'Primeira corrida oficial de 10 km',
    description: 'Completei a prova da ponte em 54 minutos, sem parar e sem dor.',
    type: 'milestone',
    lifeArea: 'corpo',
    tag: 'Corrida',
  },
  {
    id: 't-5',
    date: '2025-12-28',
    year: 2025,
    month: 'Dezembro',
    title: '14 Semanas Consecutivas de Planejamento na Trajetta',
    description: 'Ritmo semanal estabelecido sem abandonar a rotina mesmo nas férias.',
    type: 'journey_completed',
    lifeArea: 'vida',
    tag: 'Consistência',
  },
  {
    id: 't-6',
    date: '2026-03-01',
    year: 2026,
    month: 'Março',
    title: 'Início da preparação para a Meia Maratona (21k)',
    description: 'Planilha de treinamento estruturada para os próximos 8 meses.',
    type: 'goal_created',
    lifeArea: 'corpo',
    tag: 'Nova Meta',
  },
];

export const INITIAL_LIFE_SCORE: LifeScoreData = {
  corpo: {
    score: 84,
    status: 'strong',
    label: 'Forte atualmente',
    trend: 'up',
    insight: 'Frequência de treinos atingiu 3,8x/semana. O volume de sono subiu para 7h20 diárias.',
  },
  dinheiro: {
    score: 72,
    status: 'evolving',
    label: 'Em evolução',
    trend: 'up',
    insight: 'Aportes regulares há 14 semanas. Falta apenas fechar a alocação de curto prazo.',
  },
  carreira: {
    score: 88,
    status: 'strong',
    label: 'Forte atualmente',
    trend: 'stable',
    insight: 'Alta taxa de blocos de foco profundo e reconhecimento do plano estratégico.',
  },
  vida: {
    score: 64,
    status: 'attention',
    label: 'Atenção necessária',
    trend: 'down',
    insight: 'Dias intensos de trabalho reduziram o tempo de descanso desconectado no meio da semana.',
  },
};
